name: Build and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build
        env:
          SHOPIFY_DOMAIN: ${{ secrets.SHOPIFY_DOMAIN }}
          STOREFRONT_TOKEN: ${{ secrets.STOREFRONT_TOKEN }}
          API_VERSION: ${{ secrets.API_VERSION || '2023-04' }}
          CACHE_TTL: ${{ secrets.CACHE_TTL || '300000' }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files-node-${{ matrix.node-version }}
          path: dist/
          retention-days: 7

      - name: Deploy to GitHub Pages (main branch only)
        if: github.ref == 'refs/heads/main' && matrix.node-version == '20.x'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
